### ISSUE TITLE
Compile error in geolocation plugin

### ISSUE THREAD

**Issue by huberm** [sebastienblanc/geolocation#2]
When using the iwebkit plugin itself depending on geolocation 0.2 I get compile errors

e.g.:

plugins/geolocation-0.2/src/groovy/org/grails/plugins/geolocation/utils/GeoUtils.groovy: 5: unable to resolve class com.javadocmd.simplelatlng.LatLng
 @ line 5, column 1.
   import com.javadocmd.simplelatlng.LatLng;
   ^

**Comment by sebastienblanc** [comment]
Hi,
It is known issue, for now you can fix it by adding the dependency directly
in the BuildConfig.groovy of your project :

dependencies {
        // specify dependencies here under either 'build', 'compile',
'runtime', 'test' or 'provided' scopes eg.

```
    // runtime 'mysql:mysql-connector-java:5.1.13'
    runtime 'com.javadocmd:simplelatlng:1.0.0'
}
```

**Comment by huberm** [comment]
Hi Sebastien,

thought of that as well. Maybe a comment on the plugins page would be of help.

Thanks, Matthias

**Comment by IanZlik** [comment]
Hi,

I agree with huberm, just started playing with this very promising plugin and this issue pops up right on the very beginning.
As long as it is unresolved you should have something on the plugin page (which is much more informative than other plugin pages - so kudos on that).

Ian

**Comment by sebastienblanc** [comment]
Hi, I've just released 0.3 that would correct the dependency issue !

**Comment by gauravchauhan** [comment]
@huberm : If you have verified the latest release. Can you please close this issue ?

**Comment by huberm** [comment]
Tested 0.4 version with Grails 2.0. Seems to be fixed (at least my test app compiles)
