### ISSUE TITLE
Compilation fails of version 0.4 with Grails 2.0

### ISSUE THREAD

**Issue by gauravchauhan** [sebastienblanc/geolocation#3]
| Running Grails application
| Error 2012-01-17 19:19:42,786 [Thread-9] ERROR context.GrailsContextLoader  - Error executing bootstraps: Database driver [org.hsqldb.jdbcDriver] for HSQLDB not found. Since Grails 2.0 H2 is now the default database. You need to either add the 'org.h2.Driver' class as your database driver and change the connect URL format (for example 'jdbc:h2:mem:devDb') in DataSource.groovy or add HSQLDB as a dependency of your application.
Message: Database driver [org.hsqldb.jdbcDriver] for HSQLDB not found. Since Grails 2.0 H2 is now the default database. You need to either add the 'org.h2.Driver' class as your database driver and change the connect URL format (for example 'jdbc:h2:mem:devDb') in DataSource.groovy or add HSQLDB as a dependency of your application.
   Line | Method
->> 736 | invokeBeanDefiningClosure in grails.spring.BeanBuilder

---

|   569 | beans                     in     ''
|   511 | invokeMethod . . . . . .  in     ''
|   303 | innerRun                  in java.util.concurrent.FutureTask$Sync
|   138 | run . . . . . . . . . . . in java.util.concurrent.FutureTask
|   886 | runTask                   in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run . . . . . . . . . . . in     ''
^   662 | run                       in java.lang.Thread

**Comment by sebastienblanc** [comment]
Hi,
Are you sure this has something to do with the Geolocation plugin ? I see errors during the bootstraps. Do you have this error on a vanilla apps with geolocation ? Or on an exsiting app ? 
Could you try it it out with a vanilla app ? 
Thx for your interest and your feeback
Seb

**Comment by gauravchauhan** [comment]
I checked out the latest plugin and tried running the plugin itself without installing in any app and got these errors on Grails 2.0 

We can also make changes in pluginExcludes and ignore the conf files which are not being used anyway. I may be wrong here. 

I am also facing some more issues on ubuntu machine. Will create more issues this week. I am using this plugin in my application and i prefer to fix issues instead of moving on to some other js library.

By Vanilla apps do you mean a new application ?

**Comment by sebastienblanc** [comment]
Ok I understand now , running the plugin itself. Well, I will merge your pull request ! Thanks for your finding.
Vanilla  app is indeed a new app.

**Comment by gauravchauhan** [comment]
Fix merged into master.
