### ISSUE TITLE
404 error returned by ajax call which sets the geoposition

### ISSUE THREAD

**Issue by gauravchauhan** [sebastienblanc/geolocation#5]
Looking at console on Chrome. I got this  :
 "Failed to load resource: the server responded with a status of 404 (Not Found)"

On Firefox with firebug add on installed : 
"NetworkError: 404 Not Found - http://localhost:8080/testGeoLocOnGrails2/geolocation/setGeoPosition"

Even though this is harmless but it doesn't gives a good impression to end user. We can render success from the action to stop getting these errors. 

I can submit a pull request in my next commit or you can check-it in yourself.

**Comment by sebastienblanc** [comment]
Yes please make a pull request ! Thanks again

**Comment by gauravchauhan** [comment]
Committed the fix.

**Comment by gauravchauhan** [comment]
Issue must have been fixed by following commit : 

https://github.com/sebastienblanc/geolocation/commit/9bf695e348b9ccc5ff2ed3ef58cd08a0acea5dd8

**Comment by gauravchauhan** [comment]
I will verify it a new machine tomorrow and update here.

**Comment by gauravchauhan** [comment]
Fixed
